
name: Deploy to S3

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: eu-west-1
  S3_BUCKET: upsolver-devops-exercise
  S3_FILE: /vladimir.json

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build config
      id: build-config
      run: |
        cd config
        ls -l
        echo "Done"
